[workspace]
members = [
	"utopia_animations",
	"utopia_core",
	"utopia_decorations",
	"utopia_futures",
	"utopia_image",
	"utopia_layout",
	"utopia_nannou",
	"utopia_scroll",
	"utopia_text",
	"utopia_tui",
]
